# Generated by Django 5.0.3 on 2024-03-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='branch',
            name='colleges',
            field=models.ManyToManyField(to='core.college'),
        ),
        migrations.DeleteModel(
            name='Counsellor',
        ),
    ]
