# Generated by Django 5.0.3 on 2024-04-13 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_collegereviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegereviews',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='collegereviews',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
