# Generated by Django 5.0.3 on 2024-03-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_address_studentprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellorprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='counsellorprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
