# Generated by Django 5.0.3 on 2024-03-25 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_counsellorprofile_address_and_more'),
        ('core', '0002_alter_branch_options_branch_colleges_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counsellorprofile',
            old_name='student_id',
            new_name='counsellor_id',
        ),
        migrations.AddField(
            model_name='counsellorprofile',
            name='bio',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counsellorprofile',
            name='branch',
            field=models.ForeignKey(default='CSE', on_delete=django.db.models.deletion.CASCADE, to='core.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counsellorprofile',
            name='college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='counsellors', to='core.college'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counsellorprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='counsellors'),
        ),
        migrations.AddField(
            model_name='counsellorprofile',
            name='price',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='counsellorprofile',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=1),
            preserve_default=False,
        ),
    ]
