# Generated by Django 5.0.3 on 2024-03-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accesspurchase_studentprofile_counselors'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellorprofile',
            name='name',
            field=models.CharField(default='Default Name', max_length=60),
            preserve_default=False,
        ),
    ]
