# Generated by Django 5.0.3 on 2024-03-29 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_counsellorprofile_name'),
        ('core', '0003_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellorprofile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counsellors', to='core.college'),
        ),
        migrations.AlterField(
            model_name='counsellorprofile',
            name='image',
            field=models.ImageField(blank=True, default='/home/hp/project/counsellorbuddy/media/college/images/default/defaultistockphoto-1495088043-612x612.jpg', null=True, upload_to='counsellors'),
        ),
        migrations.AlterField(
            model_name='counsellorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
