# Generated by Django 5.0.3 on 2024-04-14 06:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_counsellorprofile_college_and_more'),
        ('core', '0006_alter_collegereviews_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counsellorprofile',
            options={'verbose_name_plural': 'Counsellor Profiles'},
        ),
        migrations.AlterField(
            model_name='counsellorprofile',
            name='college',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='counsellors', to='core.college'),
        ),
        migrations.AlterField(
            model_name='counsellorprofile',
            name='image',
            field=models.ImageField(blank=True, default='college/images/default/defaultistockphoto-1495088043-612x612.jpg', null=True, upload_to='counsellors'),
        ),
        migrations.AlterField(
            model_name='counsellorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counsellor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='counsellorprofile',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=(1, '1st Year')),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
