# Generated by Django 5.0.3 on 2024-04-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_counsellorprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellorprofile',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=1),
        ),
    ]
