# Generated by Django 5.0.3 on 2024-03-26 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessPurchase',
        ),
    ]
